tunnel: tunnel
credentials-file: /etc/cloudflared/<tunnel-id>.json #Change tunnel-id

ingress:
  - hostname: service.domain.com
    service: http://localhost:<service-port>
  - service: http_status:404
